version: '3.4'

networks:
  api:
    
services:
  mpserver:
    image: profile_server
    build:
      context: .
      dockerfile: MyProfile/Dockerfile
    networks:
      api:
        
  mpclient:
    image: profile_client
    build:
      context: MyProfile/ClientApp
      dockerfile: Dockerfile
    networks:
      api:
    depends_on:
      - mpserver