services:
  mp_server:
    restart: 
      on-failure:10
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50000:50000"
      - "44492:44492"
    depends_on:
      - db
    networks:
      - ext_subnet
  db:
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    image: mysql
    restart: always
networks:
  ext_subnet:
    external: 
      name: subnet    
    