version: '3.4'

networks:
  api:
    
services:
  mpserver:
    image: profile_server
    ports:
      - 80:80
    build:
      context: .
      dockerfile: MyProfile/Dockerfile
    networks:
      api:
        
  mpclient:
    image: profile_client
    ports:
      - 44492:44492
    build:
      context: .
      dockerfile: MyProfile/ClientApp/Dockerfile
    networks:
      api:
    depends_on:
      - mpserver