services:
  nothoughts:
    restart:
      on-failure:2
    env_file:
      - .env
      - redis.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "20000:20000"
      - "44492:44492"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - subnetwork
      - myprofile
  db:
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    image: mysql
    restart: always
    networks:
      - myprofile
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    depends_on: 
      - db
    image: redis:alpine
    env_file:
      - redis.env
    networks: 
      - myprofile
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    tty: true
    stdin_open: true

networks:
  myprofile:
  subnetwork:
    external: true  
    