version: '3.4'

services:
  mp_server:
    environment:
      - MYSQL_SERVER=
      - MYSQL_PORT=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
    build:
      context: .
      dockerfile: MyProfile/Dockerfile
    ports:
      - "50000:50000"
      - "44492:44492"