services:
  nothoughts:
    restart:
      on-failure:10
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50000:50000"
      - "44492:44492"
    depends_on:
      - db
    networks:
      - subnetwork
  db:
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    image: mysql
    restart: always
networks:
  subnetwork:
    external: true  
    